meta_product_name: "MealzZap"
meta_title: "MealzZap - Planner"
meta_description: "Our free weekly meal plans include a grocery shopping list and tons of easy meal planning ideas. Our delicious recipes are designed by registered dietitians and food experts to help you lose weight, eat more fiber, go vegan and more. "
meta_image: "linkedin_banner_image_1.png" # should exist in `app/assets/images/`

